Repository hyperledger-labs/splice, pull requests merged in 2025-06, with the labels that each got.

#1088 backport "SV1_SCAN_BIGQUERY deployment var; allow BQ-only cleanup (#1050)" to 0.4.1
  cluster/pulumi/canton-network/src/bigQuery.ts
  cluster/pulumi/common-sv/src/svConfigs.ts
Labels: sprint2523

#1111 [static] Add new community-contributed document
  docs/src/community/docker-compose-helm-chart.rst
  docs/src/community/index.rst
  docs/src/community/oidc-config-okta-keycloak.rst
Labels: fork

#1136 log in using GOOGLE_*_CREDENTIALS if present for CloudSQL import
  cluster/pulumi/canton-network/src/bigQuery.ts
Labels: sprint2524

#1137 backport "log in using GOOGLE_*_CREDENTIALS if present for CloudSQL import (#1136)" to 0.4.1
  cluster/pulumi/canton-network/src/bigQuery.ts
Labels: sprint2524

#387 compose, validator: Fix restoration from dump
  apps/app/src/test/scala/org/lfdecentralizedtrust/splice/integration/tests/DockerComposeValidatorFrontendIntegrationTest.scala
  cluster/compose/validator/compose-restore-from-id.yaml
  docs/src/release_notes.rst
  docs/src/validator_operator/validator_disaster_recovery.rst
Labels: fork

#1172 [static] Add new community contribution: Automated Helm/Kubernetes Templating Tool
  docs/src/community/docker-compose-helm-chart.rst
  docs/src/community/helm-kubernetes-templating-tool.rst
  docs/src/community/index.rst
Labels: static
