Repository hyperledger-labs/splice, pull requests merged in 2025-07, with the labels that each got.

#1367 Use '/usr/bin/env bash' to fix use of pre-commit hooks on nixos
  scripts/check-daml-return-types.sh
  scripts/check-daml-warts.sh
  scripts/check-trailing-whitespace.sh
Labels: static

#1416 bump helm unittest plugin
  nix/helm-unittest.nix
  nix/shell.nix
Labels: static

#1425 cluster, grafana, fix: Group "CometBFT blocks to ..." by migration id
  cluster/expected/infra/expected.json
  cluster/pulumi/infra/grafana-dashboards/canton-network/catchup.json
Labels: static

#1461 Use /usr/bin/env bash in scripts
  scripts/check-daml-interface-impls.sh
  scripts/generate-cometbft-governance-keys.sh
  scripts/generate-sv-keys.sh
  scripts/list-background-processes.sh
  scripts/list-pulumi-locks.sh
Labels: static

#1459 Source libcli.source before .envrc.validate
  .envrc
Labels: static

#1476 backport YAML-configurable GCP log alerts (#1321) to 0.4.4
  cluster/deployment/config.yaml
  cluster/deployment/mock/config.yaml
  cluster/expected/infra/expected.json
  cluster/pulumi/infra/src/config.ts
  cluster/pulumi/infra/src/gcpAlerts.ts
Labels: sprint2528

#1529 docs, fix: Move splice-info notes to unreleased
  docs/src/release_notes.rst
Labels: static

#1611 fix macos nix env
  nix/daml2js.nix
Labels: static

#1620 revert #1611 daml-sdk path change on use_enterprise=true branch
  nix/daml2js.nix
Labels: sprint2529
