Repository hyperledger-labs/splice, pull requests merged in 2025-08, with the labels that each got.

#1783 handle more special cases in minted query
  apps/app/src/test/resources/total-supply-bigquery.sql
Labels: BigQuery

#1927 Add Vagrantfile
  .gitignore
  README.vagrant.md
  Vagrantfile
  docs/src/release_notes.rst
Labels: static

#1979 mention BFT success requirement in validator onboarding doc
  docs/src/validator_operator/validator_onboarding.rst
Labels: documentation, sprint2533

#1985 vagrant: Restart nix-daemon after mounting cache
  README.vagrant.md
  Vagrantfile
Labels: static

#2076 Tokenomics in background section
  .vscode/settings.json
  docs/src/app_dev/overview/index.rst
  docs/src/background/tokenomics/cc_transfer_splice_wallet_tokenomics.rst
  docs/src/background/tokenomics/feat_app_act_marker_tokenomics.rst
  docs/src/background/tokenomics/index.rst
  docs/src/background/tokenomics/overview_tokenomics.rst
  docs/src/background/tokenomics/sv_live_tokenomics.rst
  docs/src/background/tokenomics/traffic_tokenomics.rst
  docs/src/background/tokenomics/val_live_tokenomics.rst
  docs/src/index.rst
Labels: static
